import Head from 'next/head';
import { FC, ReactNode } from 'react';
import Navbar from '../navbar/navbar';

interface Props {
    children: ReactNode
}

const Main: FC<Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>IT Com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <main>
                {children}
            </main>
        </>
    )
}

export default Main;